### PR TITLE
Notary

### PR DESCRIPTION
**Pull request by BolaNasr**
# How to run Notary 
## in kosmos run the following: 
```python

server = j.servers.gedis.configure(host="0.0.0.0", port=8888)

server.actor_add('/sandbox/code/github/threefoldtech/digitalmeX/packages/notary/actors/notary_actor.py') 

server.start()                                            
```
## using Tmux
```
cd /sandbox/code/github/threefoldtech/digitalmeX/packages/notary

moonc . &&lapis server
```

# How to use it

## to register
```
curl -d '{"robot_id":"123", "key":"test", "content":"Notary", "content_signature":"Notary_test"}' -H "Content-Type: application/json" -X POST http://localhost:8080/register
```
## to get 
```
http://localhost:8080/get?key="test"
```

## to delete 
```
http://localhost:8080/delete?robot_id="123",key="test",key_signature="Notary_test"
```

### CODE REVIEW

**Comment by rkhamis** [comment]
Great work!

Just change the casing and the location of the app and we're golden

**Comment by BolaNasr** [comment]
done

**Comment by zaibon** [comment]
@BolaNasr How do you install `moonc` and `lapis` ?

**Comment by BolaNasr** [comment]
@zaibon  
JSX at development branch 
using kosmos

```python
j.builder.runtimes.lua.install(reset=True)
j.tools.markdowndocs.test()
```

**Review by rkhamis — APPROVED** [review]

**Comment by zaibon** [comment]
not sure why this has already been merge. But this wasn't ready or finished yet.

**Pull request merged**
